version: 2.1

jobs:
  build:
    steps:
      - checkout
      - run:
          name: Build Job
          command: echo "this is the build job"
    executor:

  test:
    steps:
      - checkout
      - run:
          name: Test Job
          command: echo "this is the test job"
    executor:


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test