version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Run tests and collect coverage
          command: go test -race -coverprofile=coverage.txt -covermode=atomic
      - codecov/upload

  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn clean install
      - run:
          name: Test Job
          command: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
